
SELECT DISTINCT em.ERROR_MESSAGE,nb.DESCRIPTION,nb.PARAMETERS,nb.INSERTED_DATE,nb.HOST,nbl.ERROR_LEVEL from QMON.NIGHTLYBATCH_ERROR_MESSAGE em,
QMON.APP_NIGHTLY_BATCH nb,
QMON.APP_NIGHTLY_USERS nu,
QMON.APP_USER u,
QMON.APP_NIGHTLYBATCH_ERROR_LEVEL nbl
where(
u.APP_USER_ID =1
AND
u.FLAG='true'
AND 
em.ERROR_CODE=nb.ERROR_CODE
AND
nb.ERROR_CODE=nbl.ERROR_CODE
AND
nb.INSERTED_DATE BETWEEN '01-NOVEMBER-15 03.41.41' AND '30-NOVEMBER-15 10.52.43'
OR
em.ERROR_CODE=nb.ERROR_CODE
AND
nb.ERROR_CODE=nbl.ERROR_CODE
AND
nu.NIGHTLY_USER_ID=1
AND
nb.INSERTED_DATE BETWEEN '01-NOVEMBER-15 03.41.41' AND '01-NOVEMBER-15 03.41.41'
)
ORDER BY nb.INSERTED_DATE desc;
