Select qm.APP_QMGR_STATUS_ID,qm.QM_NAME,qm.HOSTNAME,qm.LAST_UPTIME,qm.LAST_DOWNTIME,qm.FLAG,qm.LAST_UPDATEDTIME
from QMON.APP_QMGR_STATUS qm
WHERE
qm.QM_NAME='ESBQMDEV'
AND
qm.HOSTNAME='192.168.1.50';