Select distinct mq.APP_MQ_EVENT_ID,mq.MQ_OBJECT_TYPE,mq.MQ_OBJECT_NAME,mq.MQ_QMGR_NAME,mq.MQ_OBJECT_STATUS,mq.MQ_OBJECT_DATE,mq.MQ_EVENT_HOSTNAME,mq.MQ_EVENT_INSERTED_DATE,mq.MQ_REASON_CODE,amp.EVENT_LEVEL,amp.EVENT_DESCRIPTION
from QMON.APP_MQ_EVENT mq,QMON.APP_MQEVENT_PROPERTIES amp
where amp.REASON_CODE=mq.MQ_REASON_CODE
AND
mq.MQ_QMGR_NAME='ESBQMDEV'
AND
mq.MQ_EVENT_HOSTNAME='192.168.1.50'
AND
mq.MQ_EVENT_INSERTED_DATE BETWEEN '01-OCT-15 03.41.41' AND '30-NOVEMBER-15 10.52.43'
ORDER BY mq.MQ_EVENT_INSERTED_DATE desc;