#%RAML 0.8
title: cisco-spark-integration-runtime
version: 1.0
baseUri:  https://${runtime.mule.env.raml.baseuri}/api/

traits:
  - updateOperation:
      responses:
        400:
          description: Bad Request
  - identifiedResource:
      responses:
        404:
          description: Not found
          
  - client-id-required:
      queryParameters:
        client_id:
          type: string
        client_secret:
          type: string
          
  - filteredByIntegrationStatus:
      queryParameters:
        status:
          enum: ["ONLINE", "OFFLINE"]  
          
  - filteredByIntegrationEnablement:
      queryParameters:
        enablement:
           enum: ["ACTIVE", "INACTIVE"]
           
  - filteredByInstanceStatus:
      queryParameters:
        status:
          required: true
          enum: ["ACTIVE", "INACTIVE", "DELETED"]  
           
  - filteredByUserId:
      queryParameters:
        userId:
          type: string
          
  - filteredByApplicationId:
      queryParameters:
        applicationId:
          type: integer
          
/applications:
  get:
    description: List all the applications available.
    is: [identifiedResource]
    responses:
      200:
        description: List of all applications.
        body:
          application/json:
            example: !include examples/applications/getApplicationsResponseExample.json
  /{applicationId}:
    get:
      description: Get the application details given the application Id.
      is: [identifiedResource]
      responses:
        200:
          description: Application details.
          body:
            application/json:
              example: !include examples/applications/getApplicationResponseExample.json
                   
/integrations:
  get:
    description: List all the integrations.
    is: [identifiedResource, filteredByIntegrationStatus, filteredByIntegrationEnablement]
    responses:
      200:
        description: List of active integrations.
        body:
          application/json:
            example: !include examples/integrations/getIntegrationsResponseExample.json
              
  /{integrationId}:
    get:
      description: Get the integration details given the integration Id.
      is: [identifiedResource]
      responses:
        200:
          description: Integration details.
          body:
            application/json:
              example: !include examples/integrations/getIntegrationResponseExample.json
              
    /settings:
      get:
        description: Get the settings for an specific integration
        is: [identifiedResource]
        responses:
          200:
            description: Settings of a specific integration.
            body:
              application/json:
                example: !include examples/integrations/getIntegrationSettingsResponseExample.json
                
    /appTokens:
      get:
        description: List all the integration app tokens.
        is: [identifiedResource, filteredByUserId, filteredByApplicationId]
        responses:
          200:
            description: List of all the integration app tokens.
            body:
              application/json:
                example: !include examples/integrations/tokens/getIntegrationTokensResponseExample.json
                  
      post:
        description: Create a new integration token.
        is: [updateOperation]
        body:
          application/json:
            example: !include examples/integrations/tokens/postIntegrationTokenRequestExample.json
        responses:
          201:
            description: Created
            body:
              application/json:
                example: !include examples/integrations/tokens/postIntegrationTokenResponseExample.json
      delete:
        description: Delete the token given the integrationId and userId.
        #is: [client-id-required]
        queryParameters:
          userId:
            type: string
        responses:
            200:
              description: Deleted
        
      /{appTokenId}:
        is: [updateOperation, identifiedResource]
        get:
          description: Get the token identified by tokenId
          responses:
            200:
              body:
                application/json:
                  example: !include examples/integrations/tokens/getIntegrationTokenResponseExample.json
        put:
          description: Update the token given the tokenId
          is: [updateOperation]
          body:
            application/json:
              example: !include examples/integrations/tokens/putIntegrationTokenRequestExample.json
          responses:
            202:
              description: Accepted.
        delete:
#          is: [client-id-required]
          description: Delete the token given the tokenId.
          responses:
            200:
              description: Deleted
  /instances:
      get:
        description: List all the integration instances.
        is: [identifiedResource, filteredByInstanceStatus, filteredByUserId]
        queryParameters:
          integrationId:
            type: string
          instanceUuid:
            type: string
        responses:
          200:
            description: List of all integrations instances.
            body:
              application/json:
                example: !include examples/integrations/getIntegrationInstancesResponseExample.json
      post:
        description: Create a new integration instance.
        is: [updateOperation]
        body:
          application/json:
            example: !include examples/integrations/postIntegrationInstanceRequestExample.json
        responses:
          201:
            description: Created
            body:
              application/json:
                example: !include examples/integrations/postIntegrationInstanceResponseExample.json
                
      /{instanceId}:
        is: [identifiedResource]
        get:
          description: Retrieve the details of a specific integration instance.
          responses:
            200:
              body:
                application/json:
                  example: !include examples/integrations/getIntegrationInstanceResponseExample.json
        put:
          description: Update the details of a specific integration instance.
          is: [updateOperation]
          body:
            application/json:
              example: !include examples/integrations/putIntegrationInstanceRequestExample.json
          responses:
            202:
              description: Accepted.
        delete:
#          is: [client-id-required]
          description: Delete the instance of a particular integration.
          responses:
            200:
              description: Deleted
              

/clients:  
  /appSettings:
   get:
     description: List all the client applications settings.
     is: [identifiedResource]
     responses:
       200:
         description: List of all applications.
         body:
           application/json:
             example: !include examples/applications/getApplicationsResponseExample.json
   /{integrationId}:
     get:
       description: Get the all client application details given the integration Id.
       is: [identifiedResource]
       responses:
         200:
           description: Client App Settings details.
           body:
             application/json:
               example: !include examples/clients/appsettings/getClientAppSettingsResponseExample.json
  /{clientId}:
    /tokens:
      get:
        description: Get the token details for the specific client (e.g. Spark IFrame).
        is: [identifiedResource]
        responses:
          200:
            description: List of client token.
            body:
              application/json:
                example: !include examples/clients/tokens/getClientTokensResponseExample.json
                
      post:
        description: Create a new client token.
        is: [updateOperation]
        body:
          application/json:
            example: !include examples/clients/tokens/postClientTokenRequestExample.json
        responses:
          201:
            description: Created
            body:
              application/json:
                example: !include examples/clients/tokens/postClientTokenResponseExample.json
                
      delete:
        description: Delete the client token given the integrationId and userId.
        #is: [client-id-required]
        queryParameters:
          integrationId:
            type: string
          userId:
            type: string
        responses:
            200:
              description: Deleted
      
      /{clientTokenId}:
        is: [identifiedResource]
        get:
          description: Get the client token identified by clientTokenId
          responses:
            200:
              body:
                application/json:
                  example: !include examples/clients/tokens/getClientTokenResponseExample.json
        put:
          description: Update the client token given the clientTokenId
          is: [updateOperation]
          body:
            application/json:
              example: !include examples/clients/tokens/putClientTokenRequestExample.json
          responses:
            202:
              description: Accepted.
        delete:
#          is: [client-id-required]
          description: Delete the client token given the clientTokenId.
          responses:
            200:
              description: Deleted
    /settings:
      get:
        description: Get the client application details
        is: [identifiedResource]
        queryParameters:
          applicationId:
            type: string
        responses:
          200:
            description: List of client application details.
            body:
              application/json:
                example: !include examples/clients/appsettings/getClientAppSettingsResponseExample.json
                
      post:
        description: Create a new client app settings.
        is: [updateOperation]
        body:
          application/json:
            example: !include examples/clients/appsettings/postClientAppSettingsRequestExample.json
        responses:
          201:
            description: Created
            body:
              application/json:
                example: !include examples/clients/appsettings/postClientAppSettingsResponseExample.json
      
      /{appSettingsId}:
        is: [identifiedResource]
        get:
          description: Get the client app settings identified by appSettingsId
          responses:
            200:
              body:
                application/json:
                  example: !include examples/clients/appsettings/getClientAppSettingsResponseExample.json
        put:
          description: Update the client app settings given the appSettingsId
          is: [updateOperation]
          body:
            application/json:
              example: !include examples/clients/appsettings/putClientAppSettingsRequestExample.json
          responses:
            202:
              description: Accepted.
        delete:
#          is: [client-id-required]
          description: Delete the client app settings given the appSettingsId.
          responses:
            200:
              description: Deleted
              
/dropbox:
  /settings:
    /{userId}:
      get:
        description: Send all the settings from the Database
        responses:
          200:
            description: Application details.
            body:
              application/json:
      put:
        description: Update the Dropbox Settings in Database.
        body:
          application/json:
        responses:
          200:
            description: Application details.
            body:
              application/json:
                  
    /tokensettings:
      /{instanceUuid}:
        get:
          description: Get the application details given the application Id.
          is: [identifiedResource]
          responses:
            200:
              description: Application details.
              body:
                application/json:
    post:
      description: Post all the Dropbox settings into the Database.
      body:
        application/json:
      responses:
        200:
          description: Application details.
          body:
            application/json: 

/googleDrive:
  /settings:
    /{userId}:
      get:
        description: Send all the settings from the Database
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/googledrive/settings/getGoogleDriveSettingsExample.json
      put:
        description: Update the googleDrive Settings in Database.
        body:
          application/json:
            example: !include examples/googledrive/settings/putGoogleDriveSettingsExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/googledrive/settings/operationExecutedSuccessExample.json
      post:
        description: Insert the googleDrive Settings in Database.
        body:
          application/json:
            example: !include examples/googledrive/settings/postGoogleDriveSettingsExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/googledrive/settings/operationExecutedSuccessExample.json                            
/sharePoint:
  /settings:
    /{userId}:
      get:
        description: Send all the settings from the Database
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/box/settings/getSharepointSettingsExample.json
      put:
        description: Update the SharePoint Settings in Database.
        body:
          application/json:
            example: !include examples/box/settings/putSharePointSettingsExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/googledrive/settings/operationExecutedSuccessExample.json
      post:
        description: Insert the SharePoint Settings in Database.
        body:
          application/json:
            example: !include examples/box/settings/postSharePointSettingsExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/googledrive/settings/operationExecutedSuccessExample.json                            

   
/box:
  /settings:
    /{userId}:
      get:
        description: Send all the settings from the Database
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/box/settings/getBoxSettingsExample.json
      put:
        description: Update the googleDrive Settings in Database.
        body:
          application/json:
            example: !include examples/box/settings/putBoxSettingsExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/box/settings/operationExecutedSuccessExample.json
      post:
        description: Insert the googleDrive Settings in Database.
        body:
          application/json:
            example: !include examples/box/settings/postBoxSettingsExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/box/settings/operationExecutedSuccessExample.json
                
/docusign:
  /settings:
    /{envId}:
      get:
        description: Get pdfbytes  from the Database
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/box/settings/getDocusignSettingsExample.json
  
      post:
        description: Insert the docusign  details in Database.
        body:
          application/json:
            example: !include examples/box/settings/postDocusignSettingsExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/box/settings/operationExecutedSuccessExample.json
      put:
        description: Update the docusign Settings in Database.
        body:
          application/json:
            example: !include examples/box/settings/putDocusignSettingsExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/box/settings/operationExecutedSuccessExample.json 
/certificate:
  /settings:
    /{envId}:
     get:
        description: Get pdfbytes  from the Database
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/box/settings/getDocusignSettingsExample.json
  
     post:
        description: Insert the docusign  details in Database.
        body:
          application/json:
            example: !include examples/box/settings/postDocusignSettingsExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/box/settings/operationExecutedSuccessExample.json
     put:
        description: Update the docusign Settings in Database.
        body:
          application/json:
            example: !include examples/box/settings/putDocusignSettingsExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/box/settings/operationExecutedSuccessExample.json

                     
/twitter:
  /settings:
    /{userId}:
      get:
        description: Send all the settings from the Database
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/box/settings/getBoxSettingsExample.json
      put:
        description: Update the googleDrive Settings in Database.
        body:
          application/json:
            example: !include examples/box/settings/putBoxSettingsExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/box/settings/operationExecutedSuccessExample.json
      post:
        description: Insert the googleDrive Settings in Database.
        body:
          application/json:
            example: !include examples/box/settings/postBoxSettingsExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/box/settings/operationExecutedSuccessExample.json         
               
/onedrive:
  /settings:
    /{userId}:
      get:
        description: Send all the settings from the Database
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/box/settings/getBoxSettingsExample.json
      put:
        description: Update the googleDrive Settings in Database.
        body:
          application/json:
            example: !include examples/box/settings/putBoxSettingsExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/box/settings/operationExecutedSuccessExample.json
      post:
        description: Insert the googleDrive Settings in Database.
        body:
          application/json:
            example: !include examples/box/settings/postBoxSettingsExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/box/settings/operationExecutedSuccessExample.json
                

/oneDriveBusiness:
  /settings:
    /{userId}:
      get:
        description: Send all the settings from the Database
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/box/settings/getBoxSettingsExample.json
      put:
        description: Update the oneDriveBusiness Settings in Database.
        body:
          application/json:
            example: !include examples/box/settings/putBoxSettingsExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/box/settings/operationExecutedSuccessExample.json
      post:
        description: Insert the oneDriveBusiness Settings in Database.
        body:
          application/json:
            example: !include examples/box/settings/postBoxSettingsExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/box/settings/operationExecutedSuccessExample.json
/evernote:
  /settings:
    /{evernoteUserId}:
      get:
        description: Send all the settings from the Database
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/evernote/settings/getEvernoteSettingsResponseExample.json
      post:
        description: Post Evernote Settings in Database.
        body:
          application/json:
            example: !include examples/evernote/settings/postEvernoteSettingsRequestExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/evernote/settings/postEvernoteSettingsresponseExample.json
      delete:
        description: Deletes Evernote Settings in Database.
        queryParameters:
          instanceUuid:
            type: string
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/evernote/settings/deleteEvernoteSettingsResponseExample.json
 
/trackingDetails:
  /{trackingId}:
      get:
        description: Send tracking detains by trackingId from the database
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/evernote/settings/getTrackingDetailsResponseExample.json
      post:
        description: Post tracking  details in database.
        body:
          application/json:
            example: !include examples/evernote/settings/posttrackingDetailsRequestExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/evernote/settings/postEvernoteSettingsresponseExample.json
      delete:
        description: Deletes tracking details in database.
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/evernote/settings/deleteEvernoteSettingsResponseExample.json

    
                
/office365:
  /settings:
    /{userId}:
      get:
        description: Send all the settings from the Database
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/office365/settings/getOffice365SettingsResponseExample.json
      post:
        description: Post Office365 Settings in Database.
        body:
          application/json:
            example: !include examples/office365/settings/postOffice365SettingsRequestExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/office365/settings/postOffice365SettingsresponseExample.json
      put:
        description: Put Office365 Settings in Database.
        body:
          application/json:
            example: !include examples/office365/settings/putOffice365SettingsRequestExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/office365/settings/putOffice365SettingsresponseExample.json      
      delete:
        description: Deletes Office365 Settings in Database.
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/office365/settings/deleteOffice365SettingsResponseExample.json
/googleCalendar:
  /settings:
    /{userId}:
      get:
        description: Send all the settings from the Database
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/googleCalendar/settings/getGoogleCalendarSettingsResponseExample.json
      post:
        description: Post googleCalendar Settings in Database.
        body:
          application/json:
            example: !include examples/googleCalendar/settings/postGoogleCalendarSettingsRequestExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/googleCalendar/settings/postGoogleCalendarSettingsResponseExample.json
      put:
        description: Put googleCalendar Settings in Database.
        body:
          application/json:
            example: !include examples/googleCalendar/settings/putGoogleCalendarSettingsRequestExample.json
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/googleCalendar/settings/putGoogleCalendarSettingsResponseExample.json      
      delete:
        description: Deletes googleCalendar Settings in Database.
        responses:
          200:
            description: Application details.
            body:
              application/json:
                example: !include examples/googleCalendar/settings/deleteGoogleCalendarSettingsResponseExample.json                                         